# Site settings
title: Andy Nur Web - Teach and Learning
description: Andy Nur, andynur, andy samarinda, qodr, santri qodr, andy qodr
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://andynur.my.id"

# User settings
username: Andy Nur
user_description: Manusia biasa yang ingin menjadi seorang muslim sejati.
user_title: Backend Developer
email: andynur.id@gmail.com
facebook_username: andynur.id
twitter_username: _andynur
gplus_username:  andynur
github_username:  andynur
linkedin_username:  andynur

# Google-analytics
google-analytics:
  id: "UA-150464709-1"

exclude: ['package.json', 'src' , 'node_modules']